project_id = "wxwdlyiyrqwgiwtmrajp"

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.generate-vapid-keys]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.process-abandoned-carts]
verify_jwt = false

[functions.verify-manager-code]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.create-square-payment]
verify_jwt = false

[functions.get-square-application-id]
verify_jwt = false
